const images = [
  "https://www.reliancedigital.in/medias/Apple-Accessories-Carousel-Banner-01-12-2022.jpg?context=bWFzdGVyfGltYWdlc3w4MTM2MHxpbWFnZS9qcGVnfGltYWdlcy9oMGIvaDliLzk5NjQzMzg4MDY4MTQuanBnfDg0ZjYxZjIwZTU1MWY1OTI5YTQ1MTk5NTYwYjE0ZmIwODMxYmQxNDVkMjdiYjZhYWVjZTdlYzQ3NzlhNjY5MWM",
  "https://www.reliancedigital.in/medias/PS5-Combo-Offer-Reliance-1365x260.jpg?context=bWFzdGVyfGltYWdlc3wxMzg4NDd8aW1hZ2UvanBlZ3xpbWFnZXMvaDg5L2hmNS85OTYyODAzMDY4OTU4LmpwZ3w2NTFhMDczMTg2ZjhjYzIxNmQzNWM5ZDM2MGU2MTQ2N2Y2N2ZiMTM1OTQ0YjRkNjY1N2VmM2M1ZTY1MGY5ODQ2",
  "https://www.reliancedigital.in/medias/Pre-Summer-Sale-Carousel-Banner-Desktop.jpg?context=bWFzdGVyfGltYWdlc3w5MzYyMXxpbWFnZS9qcGVnfGltYWdlcy9oNjMvaDAxLzk5NjM4NTI2NjA3NjYuanBnfGQzNmMzZjYyNGYwNWFhOWYyNjAzNjMzYjgyYzA4YmE3ZTFlNzBhZTgwMzFkNWY0MDYyZTIwYzEzZjhjNDJjZmU",
  "https://www.reliancedigital.in/medias/MIdnight-Sale-Carousel-07-12-2022.jpg?context=bWFzdGVyfGltYWdlc3w5OTA2OXxpbWFnZS9qcGVnfGltYWdlcy9oNzYvaGM5Lzk5MjgzODQ4Mzk3MTAuanBnfGUxZTBiNDNlOGU2ZWUzMzg2YjU3MWMwYmJiNTBhZjM5ODdkMzhjYjNiYWZhYzllYWJmNzE0MGY4MTFmMjY3MDU",
  "https://www.reliancedigital.in/medias/Clearance-Sale-on-Everyday-Appliances-Carousel-Banner-Desktop.jpg?context=bWFzdGVyfGltYWdlc3w5MjQ3MHxpbWFnZS9qcGVnfGltYWdlcy9oMDkvaDljLzk5NjQzMzk4ODgxNTguanBnfDNjODg3NzQ1NjYyYjk5ZWQyNWI4Mjk5YWI5YzMxMWI3ZWEzOGUwMTZhZThjY2YzODRmOGJkODgzOTUxNjc0Mzc",
  "https://www.reliancedigital.in/medias/Samsung-Galaxy-S23-Series-CLP-Banner-Desktop.jpg?context=bWFzdGVyfGltYWdlc3w5NjUyNnxpbWFnZS9qcGVnfGltYWdlcy9oZjcvaDQ5Lzk5NjA4ODU3ODA1MTAuanBnfGRkM2Y5OTExODVjYzYwNmY2ZWFhMDRjZDUzODhjMTAwNWRjNjQ5Yjg0NmI2ZTQzZGQ0MDViNmNhMTg2ZDJkZDc",
  "https://www.reliancedigital.in/medias/Personal-Care-Carousel-Banner-21-02-2023.jpg?context=bWFzdGVyfGltYWdlc3w3NjA0OHxpbWFnZS9qcGVnfGltYWdlcy9oZGQvaDA0Lzk5NjQzNDAwMTkyMzAuanBnfDYwNDkxMGU4MDIyMzgzYWI0MWQ5NWZjNzZmMGMwMWNmMjg4NmU1YWE0ZDg1MWUxMTE3NmVkZGZmNjdhOTc1NjA",
  "https://www.reliancedigital.in/medias/OnePlus-Buds-Pro-2-CLP-Banner-14-02-2023.jpg?context=bWFzdGVyfGltYWdlc3w1NTEwN3xpbWFnZS9qcGVnfGltYWdlcy9oMGYvaDE3Lzk5NjA4ODU2NDk0MzguanBnfGI5ZTY2YWFhMmVmOWQ2N2YwZTcwM2JkODBmYzRlZWJjMWIxYjkxN2FkMWFlOTkyZTk5MGQ3OGE2OWI2NDI4Mjg",
  "https://www.reliancedigital.in/medias/Televisions-Carousel-Banner-03-02-2023.jpg?context=bWFzdGVyfGltYWdlc3w5NTA1NXxpbWFnZS9qcGVnfGltYWdlcy9oOTQvaGRmLzk5NTc2NTM2MTA1MjYuanBnfDZhZmEzYzdjNDcxNGQ0NjkxYjgxNzIyN2U1YWQxNjZiNTc1Y2Y5ODI5YzBmNjJmOWIxNDFjYmI0Y2M4Zjg5Y2I",
  "https://www.reliancedigital.in/medias/Latest-Laptops-Carousel-Banner-01-02-2023.jpg?context=bWFzdGVyfGltYWdlc3w4MDQyOXxpbWFnZS9qcGVnfGltYWdlcy9oYjIvaDZiLzk5NTk0OTQxMjM1NTAuanBnfDdiYzY2NjJlZGFkMmRlZTgzZGI3NWRiOWU5ZDNhYWIyNzEwODdiN2E1YjBiY2NiOTZhNjMxZWM4NGQxYjAxODg",
];


export default images;