let products=[
    {
        title:"boAt Airdopes 138 Twin Wireless Earbuds with IWP Technology, Bluetooth V5.0, 15 hrs playtime, Immersive Audio, Instant Voice Assistant and Type-C Charging with 1 year warranty, Steel Blue",
        images:["https://www.reliancedigital.in/medias/boAt-Airdopes-138-Airdopes-491973383-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wyMTAwMnxpbWFnZS9qcGVnfGltYWdlcy9oYmUvaGYwLzk5MDQ0ODY0ODE5NTAuanBnfDMwOTI2ZGM0NzA3ZmFmMWY3YzI4MjA1MDQ3NmFiOTM3Njk0ZTUyMGMyMWJlZTM4Y2QwYmQ0MGM4OTBjMjAzZmU"],
        brand:"boAt",
        category:"Headphones & Headsets",
        price:999,
        mrp:2990,
        discount:67,
    },
    {
        title:"boAt Flash Edition Smart Watch with Activity Tracker, Multiple Sports Modes, 3.3 cm (1.3 inch) Screen, 170 plus Watch Faces, Camera & Music Control, IP68 & 7 Days Battery Life(Galaxy Blue)",
        images:["https://www.reliancedigital.in/medias/boAt-Watch-Flash-RTL-Smart-Watches-492574196-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wzNjQyNzF8aW1hZ2UvanBlZ3xpbWFnZXMvaDc0L2g4YS85NzU1Nzc4Njc4ODE0LmpwZ3wxY2E2Njg1ZDE3ODQxZDk5MmRlYzQ1NjMyMDA0M2U3NTI2Yzg1YjRkNmI5OTgwYjZhNDdiZjZjMDQ3OThhMTQy"],
        brand:"boAt",
        category:"Smartwatches",
        price:1299,
        mrp:6990,
        discount:81,
    },
    {
        title:"boAt Rockerz 235V2  bluetooth Wireless Neckband with IPX5 Sweat and Water Resistance, Fast Charge, 8Hrs Playback, magnetic earbuds (Red)",
        images:["https://www.reliancedigital.in/medias/Boat-Rockerz-235-V2-Earphones-492579328-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w2MTM1M3xpbWFnZS9qcGVnfGltYWdlcy9oZmMvaDM3Lzk3NjUzNzMyMTQ3NTAuanBnfGI2NjNkY2IyYmY5M2FlOGRlZTg4MjY1NWVjMmIyMWE2YjIyZjFlZWI1OTA2ZmIwNGVjYjEzOTRiMmI0Mzk5ZWQ"],
        brand:"boAt",
        category:"Headphones & Headsets",
        price:799,
        mrp:2990,
        discount:73,
    },
    {
        title:"boAt Wave Lynk Voice Smartwatch with Bluetooth Calling, Active Black",
        images:["https://www.reliancedigital.in/medias/boAt-Lynk-Voice-Smart-Watch-493664886-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w3MzI3NnxpbWFnZS9qcGVnfGltYWdlcy9oMWQvaDIwLzk5NDk3Njk0MzMxMTguanBnfDNjZGNiYWVhM2VhZjI0OTgzNGRiYWI4ZGY5Nzg1YmEwNmFmMDZmOWRkMGM1YzVhYmI3YzFmOGNmMjVjMDE3MjY"],
        brand:"boAt",
        category:"Smartwatches",
        price:1999,
        mrp:6499,
        discount:69,
    },
    {
        title:"boAt Airdopes 148 Bluetooth Truly Wireless in Ear Earbuds with mic, 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Gaming, ENx Tech, ASAP Charge, IWP, IPX4 Water Resistance with 1 year warranty (Active Black)",
        images:["https://www.reliancedigital.in/medias/boAt-Airdopes148-TrueWireless-492579512-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wxNDY3NzV8aW1hZ2UvanBlZ3xpbWFnZXMvaGE0L2g2Mi85ODE2NDAxMzEzODIyLmpwZ3w4MTM4ZGI2MWNmOGFlNTUxMjg1ODMzY2FmY2UxZjczNWY1OTBmZjE2ZDQyMzNkNTI4ZWIxYTlkZjA5ZGY4ODAz"],
        brand:"boAt",
        category:"Headphones & Headsets",
        price:1349,
        mrp:4490,
        discount:70,
    },
    {
        title:"boAt Flash Edition Smart Watch with Activity Tracker, Multiple Sports Modes, 3.3 cm (1.3 inch) Screen, 170 plus Watch Faces, Camera & Music Control, IP68 & 7 Days Battery Life(Moon Red)",
        images:["https://www.reliancedigital.in/medias/boAt-Watch-Flash-RTL-Smart-Watches-492574194-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wzNzczODl8aW1hZ2UvanBlZ3xpbWFnZXMvaGE1L2hmOS85NzU1Nzc5MDA2NDk0LmpwZ3xmNTJkODYxM2ViOTNmMTUzMTc1ZjAwOWQyMTRkYzRmYzdiYjJmYmYwOTZhZDc2NmUyMDI3YzllNjk1YTRiYzJk"],
        brand:"boAt",
        category:"Smartwatches",
        price:1299,
        mrp:6990,
        discount:81,
    },
    {
        title:"boAt Aavante Bar 908 2.0 Channel Sound Bar with 30 Watt RMS Power Output, Black",
        images:["https://www.reliancedigital.in/medias/boAt-Aavante-Bar-908-Sound-Bar-493179276-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3w1MDk4M3xpbWFnZS9qcGVnfGltYWdlcy9oMDMvaDJkLzk5MTA4MDE4OTEzNTguanBnfDZkMDYyYTQyZDg3ZTYyMzUxYTAwMjhlMTE2ZGYzYzExNTI0ZWMxNGQ5NWEwNGE0YTJiMDdmMjMzNTA5ZjZiNDg"],
        brand:"boAt",
        category:"TV Speakers & Soundbars",
        price:2499,
        mrp:5990,
        discount:58,
    },
    {
        title:"boAt Wave Lynk Voice Smartwatch with Bluetooth Calling, Grey",
        images:["https://www.reliancedigital.in/medias/boAt-Lynk-Voice-Smart-Watch-493664887-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wxMDAwOTF8aW1hZ2UvanBlZ3xpbWFnZXMvaDc4L2gyZi85OTQ5NzY5MTA1NDM4LmpwZ3xjYzJlMzFhMzAxYjNkMDdjNTA5ODc2YjE5N2NmYjNjOWQzMTRjMmI1ZGNhZTdkNTA0ZjJhNDIzYjkxMGU5ZGI0"],
        brand:"boAt",
        category:"Smartwatches",
        price:1999,
        mrp:6499,
        discount:69,
    },
    {
        title:"boAt Rockerz 255 Pro in Ear Bluetooth Neckband with Upto 10 Hours Playback, ASAP Charge, IPX5, boAt Signature Sound & Integrated Controls, Red",
        images:["https://www.reliancedigital.in/medias/boAt-Rockerz-255-Pro-Airdopes-492913062-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wzNDkzMHxpbWFnZS9qcGVnfGltYWdlcy9oM2MvaDIyLzk5MDQ1MjQxNjUxNTAuanBnfDBmN2JlMjkxM2UxMDUyODhhNGM3ZWNhNGZkY2FjNTUzNDJhZDE2ZTQ2ZmRhNzhjNDY5YmJlMDFmZjcyNTQxN2E"],
        brand:"boAt",
        category:"Headphones & Headsets",
        price:1299,
        mrp:3499,
        discount:63,
    },
    {
        title:"boAt Wave Play Smart Watch 4.30 cm (1.69 inch) HD Display, Heart Rate, SpO2 and Sleep Monitor, Multiple Sports Mode, Health Ecosystem, 100+ Cloud Based Watch Faces, WARM GREY",
        images:["https://www.reliancedigital.in/medias/boAt-Wave-Play-Smart-Watch-493178420-i-1-1200Wx1200H?context=bWFzdGVyfGltYWdlc3wxNjI2NDN8aW1hZ2UvanBlZ3xpbWFnZXMvaDE1L2gzMi85OTE1NzE3NTgyODc4LmpwZ3w1YmQ0ZGUzOWQyZTM2NDk3YzkwM2EyYjM3NTgxYzEzZjdmMTRmYmFjZTY1ZTM3YTBmYmJiNjJkOTAyZDEyZDY4"],
        brand:"boAt",
        category:"Smartwatches",
        price:1549,
        mrp:5990,
        discount:74,
    },
]

export default products


// {
//     title:"",
//     images:[""],
//     brand:"",
//     category:"",
//     price:,
//     mrp:,
//     discount:,
// }